#pragma once

// TODO: add to all Do function
typedef enum
{
	CODE_OK = 0,
	CODE_ERROR,
	CODE_NOT_FOUND_DEVICE,
	CODE_NOT_FOUND_GROUP,
	CODE_NOT_FOUND_SCENE,
	CODE_NOT_FOUND_RULE,
	CODE_NOT_FOUND_ROOM,
	CODE_FORMAT_ERROR,
	CODE_DATABASE_ERROR,
	CODE_MEMORY_ERROR,
} ErrorCode;