VERSION = 2.0.0

ZIGBEE = OFF

CC ?= gcc
CXX ?= g++
OBJEXT ?= .o
BUILD_PATH = build

CFLAGS ?= -Wno-unused-function -fno-integrated-as -fstrict-aliasing -fPIC -Os -ffunction-sections -fdata-sections
CXXFLAGS ?= -std=c++17 -Os -ffunction-sections -fdata-sections -Wno-unused-result -Wno-deprecated-declarations
LDFLAGS ?= -Wl,--gc-sections -Os -ffunction-sections -fdata-sections
LDFLAGS += -static-libstdc++

INCLUDES += -I. -Ibutton -Iconfig -Idatabase -Iobject -Idevice -Idevice/ble -Igateway -Igroup -Iroom -Ijson -Ilog -Imqtt -Ihttp -Iprotocol/ble -Irule -IsceneBle -Iuart -Iutil -Iwifi -Ifile -Iota
DEFINES = -DVERSION=$(VERSION) -DCONFIG_USE_OLD_APP=0 -DCONFIG_USE_MQTT_V2=1
# DEFINES += -DCONFIG_SAVE_ATTRIBUTE
LINKEDLIBS = -lmosquittopp -lsqlite3 -pthread -lcurl

ifeq ($(ZIGBEE),ON)
	INCLUDES 	+= -Idevice/zigbee -Iprotocol/zigbee
	DEFINES 	+= -DCONFIG_ENABLE_ZIGBEE=1

	DEVICESRC += $(wildcard protocol/zigbee/*.cpp)
	DEVICESRC += $(wildcard device/zigbee/*.cpp)
	DEVICESRC += $(wildcard device/zigbee/cluster/*.cpp)
	DEVICESRC += $(wildcard device/zigbee/cluster/onoff/*.cpp)
	DEVICESRC += $(wildcard device/zigbee/cluster/onoff/attribute/*.cpp)
endif

DEVICESRC += $(wildcard button/*.cpp)
DEVICESRC += $(wildcard config/*.cpp)
DEVICESRC += $(wildcard database/*.cpp)
DEVICESRC += $(wildcard object/*.cpp)
DEVICESRC += $(wildcard device/*.cpp)
DEVICESRC += $(wildcard device/ble/*.cpp)
DEVICESRC += $(wildcard device/ble/module/*.cpp)
DEVICESRC += $(wildcard device/ble/element/*.cpp)
DEVICESRC += $(wildcard gateway/*.cpp)
DEVICESRC += $(wildcard room/*.cpp)
DEVICESRC += $(wildcard group/*.cpp)
DEVICESRC += $(wildcard json/*.cpp)
DEVICESRC += $(wildcard log/*.cpp)
DEVICESRC += $(wildcard mqtt/*.cpp)
DEVICESRC += $(wildcard http/*.cpp)
DEVICESRC += $(wildcard protocol/ble/*.cpp)
DEVICESRC += $(wildcard rule/*.cpp)
DEVICESRC += $(wildcard sceneBle/*.cpp)
DEVICESRC += $(wildcard uart/*.cpp)
DEVICESRC += $(wildcard util/*.cpp)
DEVICESRC += $(wildcard wifi/*.cpp)
DEVICESRC += $(wildcard file/*.cpp)
DEVICESRC += $(wildcard ota/*.cpp)

CPPSRC = $(wildcard *.cpp) $(DEVICESRC)
CPPOBJ = $(CPPSRC:.cpp=$(OBJEXT))
BUILTOBJ = $(addprefix $(BUILD_PATH)/,$(CPPOBJ))

APP = smh

all: $(APP)

.PHONY: all $(APP) clean

$(APP): $(BUILTOBJ)
	$(CXX) $(LDFLAGS) -o $@ $(BUILTOBJ) $(LINKEDLIBS)
	
$(BUILD_PATH)/%.o: %.cpp
	@mkdir -p $(@D)
	$(CXX) $(CXXFLAGS) $(DEFINES) $(INCLUDES) -c $< -o $@

$(BUILD_PATH)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CFLAGS) $(DEFINES) $(INCLUDES) -c $< -o $@
	
install: $(APP)
	install -d $(DESTDIR)$(PREFIX)/bin/
	install -m 744 $(APP) $(DESTDIR)$(PREFIX)/bin/

clean: 
	rm -rf $(APP) $(BUILD_PATH)
