#pragma once

#define ZIGBEE_SUCCESS 0x00

#define ZIGBEE_DATATYPE_NULL 0x00

#define ZIGBEE_DATATYPE_BOOL 0x10

#define ZIGBEE_DATATYPE_UINT8 0x20
#define ZIGBEE_DATATYPE_UINT16 0x21
#define ZIGBEE_DATATYPE_INT16 0x29

#define ZIGBEE_DATATYPE_ENUM8 0x30

#define ZIGBEE_DATATYPE_STRING 0x42
#define ZIGBEE_DATATYPE_STRUCT 0x4C